name: Daily CSV Logging

on:
  repository_dispatch:
    types: [daily_trigger]

jobs:
  logging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas openpyxl
        
      - name: Run CSV Logger
        run: python csv_logger.py
        
      - name: Commit and Push
        run: |
          git config --global user.name "hoon-d-machine"
          git config --global user.email "hoon-d-machine@users.noreply.github.com"
          git add data/*.csv
          git commit -m "Update CSV logs: $(date +'%Y-%m-%d')" || echo "No changes"
          git push
