name: Qoo10 Auto Scraper

on:
  schedule:
    # 매일 4번 실행 (한국 시간: 오전 3시, 12시, 오후 6시, 11시)
    # cron은 UTC 기준이라 한국 시간 -9시간입니다. (18, 0, 6, 12)
    - cron: '0 3,9,14,18 * * *'
  workflow_dispatch: # 수동으로 버튼 눌러서 실행할 수 있게 함

jobs:
  scrape_and_save:
    runs-on: ubuntu-latest
    
    # 아까 설정한 비밀번호들을 일꾼에게 전달
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      EVENT_SID: ${{ secrets.EVENT_SID }}
    
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: 파이썬 설치 (3.9버전)
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 필요한 도구 설치
        run: pip install -r requirements.txt

      - name: 수집기 실행
        run: python collector.py
